folioapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('folioapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

folioapp/models.py
from django.db import models

# HOME SECTION

class Home(models.Model):
    name = models.CharField(max_length=20)
    greetings_1 = models.CharField(max_length=5)
    greetings_2 = models.CharField(max_length=5)
    picture = models.ImageField(upload_to='picture/')
    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ABOUT SECTION

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About,
                                on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)



# SKILLS SECTION

class Category(models.Model):
    name = models.CharField(max_length=20)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name

class Skills(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)

    

# PORTFOLIO SECTION

class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return f'Portfolio {self.id}'

folioapp/views.py
from django.shortcuts import render
from .models import Home, About, Profile, Category, Skills, Portfolio

def index(request):

    # Home
    home = Home.objects.latest('updated')

    # About
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)

    # Skills
    categories = Category.objects.all()

    # Portfolio
    portfolios = Portfolio.objects.all()
    

    context = {
        'home': home,
        'about': about,
        'profiles': profiles,
        'categories': categories,
        'portfolios': portfolios
    }


    return render(request, 'index.html', context)

folioapp/templates/index.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Rupam Chakraborty</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                
                <div>
                    <a href="/" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>{{ home.greetings_1 }}</span><br>{{ home.greetings_2 }}</h1>

                    

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>
                    
                    <div class="home__img">
                        <img src="{{ home.picture.url }}" alt="">
                    </div>

                    <!-- <div class="home_img">
                        <img src="{{ home.picture.url }}" alt="">
                    </div> -->

                </div>
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">About</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <!-- <img src="{% static 'assets/img/perfil.png' %}" alt=""> -->
                        <img src="{{ about.profile_img.url }}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{ about.heading }}</h2>
                        <span class="about__profession">{{ about.career }}</span>
                        <p class="about__text">{{ about.description }}</p>

                        <div class="about__social">

                            {% for profile in about.profile_set.all %}
                                <a href="{{ profile.link }}" class="about__social-icon">
                                    <i class='bx bxl-{{ profile.social_name }}' ></i>
                                </a>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>
            </section>

            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        {% for category in categories %}
                        <h3 class="skills__subtitle">{{category.name}}</h3>
                            {% for skills in category.skills_set.all %}
                            
                                <span class="skills__name">{{skills.skill_name}}</span>
                            {% endfor %}
                        {% endfor %}
                        
                    </div>

                    <div class="skills__img">
                        <img src="{% static 'assets/img/skill.jpg' %}" alt="">
                    </div>
                </div>
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">Portfolio</h2>

                
                <div class="portfolio__container bd-grid">

                    {% for portfolio in portfolios %}
                    
                    <div class="portfolio__img">
                        <img src="{{ portfolio.image.url }}" alt="">

                        <div class="portfolio__link">
                            <a href="{{ portfolio.link }}" class="portfolio__link-name">View details</a>
                        </div>
                    </div>

                    {% endfor %}
                    
                </div>
                
            </section>

            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Contact</h2>

                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text">rupam.3220@gmail.com</span>

                        <h3 class="contact__subtitle">ADRESS</h3>
                        <span class="contact__text">Kolkata, West Bengal, India</span>
                    </div>

                    <div class="contact__info">

                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">+91 7687917297</span>

                    </div>

                    <form action="" class="contact__form">
                        <div class="contact__inputs">
                            <input type="text" placeholder="Name" class="contact__input">
                            <input type="mail" placeholder="Email" class="contact__input">
                        </div>

                        <textarea name="" id="" cols="0" rows="10" class="contact__input"></textarea>

                        <input type="submit" value="Send" class="contact__button">
                    </form>
                </div>
            </section>
        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">Rupam Chakraborty</h2>
                    <p class="footer__text">Hi there, This is my portfolio website.</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Home</a></li>
                        <li><a href="#about" class="footer__link">About</a></li>
                        <li><a href="#skills" class="footer__link">Skills</a></li>
                        <li><a href="#portfolio" class="footer__link">Portfolio</a></li>
                        <li><a href="#Contact" class="footer__link">Contact</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">FOLLOW</h2>
                    <a href="https://github.com/Rupam3220" class="footer__social"><i class='bx bxl-github' ></i></a>
                    <a href="https://bitbucket.org/rupampersonal/workspace/overview/" class="footer__social"><i class='bx bxl-gitlab' ></i></a>
                    <a href="https://www.linkedin.com/in/rupam-chakraborty-345258196/" class="footer__social"><i class='bx bxl-linkedin' ></i></a>
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>